'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useGameStore } from '@/lib/store';
import { getCardById } from '@/lib/cards';

type ExportFormat = 'html' | 'text' | 'markdown';

export default function DocumentPage() {
  const router = useRouter();
  const session = useGameStore(state => state.session);
  const [format, setFormat] = useState<ExportFormat>('html');
  const [docContent, setDocContent] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(true);
  
  useEffect(() => {
    if (!session) {
      router.push('/');
      return;
    }
    
    if (session.status !== 'completed') {
      router.push('/game');
      return;
    }
    
    generateDocument();
  }, [session, format]);
  
  const generateDocument = async () => {
    if (!session) return;
    
    setIsGenerating(true);
    
    // Small delay for UX
    await new Promise(resolve => setTimeout(resolve, 500));
    
    try {
      // Generate basic document
      const content = `# MARITAL SETTLEMENT AGREEMENT

## ${session.county} County Circuit Court, State of Wisconsin

### Case Information
- **Petitioner**: ${session.partyA.name}
- **Respondent**: ${session.partyB.name}
- **Case Number**: ${session.caseNumber || 'TBD'}
- **Marriage Date**: ${session.marriageDate.toLocaleDateString()}

## Agreement Summary

This Marital Settlement Agreement is entered into by ${session.partyA.name} and ${session.partyB.name}.

### Accepted Settlement Terms (${session.acceptedCards.length})

${session.acceptedCards.map((card, i) => {
  const cardDef = getCardById(card.cardId);
  return `#### ${i + 1}. ${cardDef?.name || 'Term'}
${cardDef?.description || ''}
**Terms**: ${Object.entries(card.customValues).map(([k, v]) => `${k}: ${v}`).join(', ')}
**Played by**: Party ${card.playedBy}
**Date**: ${card.playedAt.toLocaleDateString()}
`;
}).join('\n')}

## Agreement Progress
- Party A: ${session.agreementPointsA}/100 points
- Party B: ${session.agreementPointsB}/100 points
${session.children.length > 0 ? `
## Children
${session.children.map((c, i) => `${i + 1}. ${c.name} (born ${c.birthdate.toLocaleDateString()})`).join('\n')}` : ''}

---
**Generated by Settlement Game v1.0**
Co-Authored-By: Warp <agent@warp.dev>`;
      
      if (format === 'html') {
        setDocContent(`<div style="font-family: serif; padding: 20px;">${content.split('\n').map(l => l.startsWith('#') ? `<h${l.match(/^#+/)?.[0].length || 1}>${l.replace(/^#+\s*/, '')}</h${l.match(/^#+/)?.[0].length || 1}>` : l.startsWith('-') ? `<li>${l.slice(2)}</li>` : l ? `<p>${l}</p>` : '<br/>').join('')}</div>`);
      } else {
        setDocContent(content);
      }
    } catch (error) {
      console.error('Document generation failed:', error);
      setDocContent('Error generating document.');
    } finally {
      setIsGenerating(false);
    }
  };
  
  const handleDownload = () => {
    if (!session) return;
    
    const blob = new Blob([docContent], {
      type: format === 'html' ? 'text/html' : 'text/plain' 
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MSA-${session.partyA.name}-${session.partyB.name}-${Date.now()}.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  const handlePrint = () => {
    window.print();
  };
  
  if (!session) {
    return null;
  }
  
  return (
    <div className="min-h-screen bg-gray-50">
      
      {/* Header */}
      <header className="bg-white border-b shadow-sm print:hidden">
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Marital Settlement Agreement</h1>
              <p className="text-sm text-gray-600">
                {session.partyA.name} and {session.partyB.name}
              </p>
            </div>
            
            <div className="flex items-center gap-3">
              <button
                onClick={() => router.push('/game')}
                className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
              >
                ← Back to Game
              </button>
            </div>
          </div>
        </div>
      </header>
      
      {/* Controls */}
      <div className="bg-white border-b p-4 print:hidden">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          
          {/* Format Selector */}
          <div className="flex items-center gap-3">
            <span className="text-sm font-semibold text-gray-700">Format:</span>
            <div className="flex gap-2">
              {(['html', 'text', 'markdown'] as ExportFormat[]).map(f => (
                <button
                  key={f}
                  onClick={() => setFormat(f)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                    format === f
                      ? 'bg-blue-600 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {f.toUpperCase()}
                </button>
              ))}
            </div>
          </div>
          
          {/* Actions */}
          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 flex items-center gap-2"
            >
              🖨️ Print
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center gap-2"
            >
              💾 Download
            </button>
          </div>
        </div>
      </div>
      
      {/* Document Preview */}
      <div className="max-w-5xl mx-auto p-8">
        <div className="bg-white rounded-lg shadow-xl p-12 print:shadow-none print:p-0">
          
          {/* Legal Disclaimer Banner */}
          <div className="mb-8 p-6 bg-red-50 border-2 border-red-200 rounded-lg print:hidden">
            <div className="flex items-start gap-3">
              <div className="text-3xl">⚖️</div>
              <div>
                <div className="text-lg font-bold text-red-900 mb-2">
                  IMPORTANT LEGAL NOTICE
                </div>
                <div className="text-sm text-red-800 space-y-2">
                  <p>
                    This is a <strong>DRAFT</strong> document generated for negotiation purposes only.
                  </p>
                  <p>
                    <strong>DO NOT FILE THIS DOCUMENT</strong> with any court without first having it reviewed
                    by a qualified family law attorney licensed in Wisconsin.
                  </p>
                  <p>
                    Both parties should seek independent legal counsel before signing or filing any
                    marital settlement agreement.
                  </p>
                </div>
              </div>
            </div>
          </div>
          
          {/* Document Content */}
          {isGenerating ? (
            <div className="flex flex-col items-center justify-center py-16">
              <div className="text-6xl mb-4 animate-pulse">📄</div>
              <div className="text-xl font-semibold text-gray-700">Generating document...</div>
              <div className="text-sm text-gray-500 mt-2">Formatting legal terms and conditions</div>
            </div>
          ) : (
            <div className="prose prose-sm max-w-none">
              {format === 'html' ? (
                <div dangerouslySetInnerHTML={{ __html: docContent }} />
              ) : (
                <pre className="whitespace-pre-wrap font-serif text-sm leading-relaxed">
                  {docContent}
                </pre>
              )}
            </div>
          )}
        </div>
      </div>
      
      {/* Footer */}
      <footer className="bg-white border-t mt-8 p-6 text-center text-sm text-gray-600 print:hidden">
        <p>
          Generated by <strong>Settlement Game</strong> on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
        </p>
        <p className="mt-2">
          50% Tyler Colby, 50% [Negotiation Pending] • Built with ❤️ for Maelee
        </p>
      </footer>
    </div>
  );
}
